/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.Group;
import Backend.GroupDataBase;
import Backend.GroupManagement;
import Backend.User;
import Backend.UserDataBase;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author daree
 */
public class primaryAdminManageAdmins extends javax.swing.JFrame {

    UserDataBase userDB = UserDataBase.getDatabase();
    primaryAdminFrame primaryFrame;
    GroupManagement groupmanage = new GroupManagement();
    GroupDataBase GDB = GroupDataBase.getInstance();
    Group group;

    /**
     * Creates new form primaryAdminFrame
     */
    public primaryAdminManageAdmins(primaryAdminFrame primaryFrame) {
        initComponents();
        this.primaryFrame = primaryFrame;
        this.group = GDB.getCurrentGroup();
        filllist();
    }

    public void filllist() {

        // this.group = GDB.getCurrentGroup();
        ArrayList<String> adminsIDs = group.getAdminsIDs();
        DefaultListModel<String> model = new DefaultListModel();

        for (String ID : adminsIDs) {
            User Admin = userDB.getUserById(ID);
            String adminName = Admin.getUsername();
            model.addElement(adminName);

        }

        if (model.isEmpty()) {
            list.setModel(new DefaultListModel<>());
            jScrollPane1.setViewportView(list);
        } else {

            list.setModel(model);
            jScrollPane1.setViewportView(list);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        demotebtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        backtbn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        demotebtn.setText("demote");
        demotebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demotebtnActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(list);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("  Admins");

        backtbn.setText("back");
        backtbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtbnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(demotebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(backtbn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(demotebtn)
                        .addGap(239, 239, 239)
                        .addComponent(backtbn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void demotebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demotebtnActionPerformed
        // TODO add your handling code here:

        int index = list.getSelectedIndex();
        if (index > -1) {
            String memberName = list.getSelectedValue();
            User Member = userDB.getUserByUsername(memberName);
            groupmanage.DemoteFromAdmin(Member.getUserId(), group.getGroupName());
            filllist();

        } else {
            JOptionPane.showMessageDialog(this, "You Should Select an admin to demote", "  Message ", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_demotebtnActionPerformed

    private void backtbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtbnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        primaryFrame.setVisible(true);
    }//GEN-LAST:event_backtbnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        setVisible(false);
        primaryFrame.setVisible(true);
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backtbn;
    private javax.swing.JButton demotebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list;
    // End of variables declaration//GEN-END:variables
}
