/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.Group;
import Backend.GroupDataBase;
import Backend.GroupManagement;
import Backend.Management;
import Backend.Post;
import Backend.User;
import Backend.UserDataBase;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class primaryAdminGroup extends javax.swing.JFrame {
  private Newsfeed n;
    private UserDataBase userDatabase = UserDataBase.getDatabase();
    private GroupDataBase groupDatabase = GroupDataBase.getInstance();
    private User user = userDatabase.getCurrentUser();
    private GroupManagement manager;
    private Group currentGroup;
    private DefaultListModel<String> memberListModel;
    private JList<String> memberList;
    private JList<String> adminList;
private DefaultListModel<String> adminListModel;
   
      
    /**
     * Creates new form primaryAdminGroup
     */
    public primaryAdminGroup(Newsfeed n, GroupManagement manager, String groupName) {
        initComponents();
        this.n = n;
        this.manager = manager;
        this.user = userDatabase.getCurrentUser();
        this.currentGroup = groupDatabase.getGroupByname(groupName);
        populateMemberList();
        populateAdminList();
    }
    private void populateMemberList() {
        memberListModel.clear();
        List<User> members = currentGroup.getMembers();
        for (User member : members) {
            memberListModel.addElement(member.getUsername());
        }
    }
     private void populateAdminList() {
        adminListModel.clear();
        List<User> admins = currentGroup.getMembers();
        for (User admin : admins) {
            memberListModel.addElement(admin.getUsername());
        }
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        promote = new javax.swing.JButton();
        demote = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        managePosts = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        promote.setText("promote admin");
        promote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promoteActionPerformed(evt);
            }
        });

        demote.setText("demote admin");
        demote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demoteActionPerformed(evt);
            }
        });

        delete.setText("Delete Group");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        managePosts.setText("Manage Posts");
        managePosts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePostsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(promote)
                .addGap(18, 18, 18)
                .addComponent(demote)
                .addGap(18, 18, 18)
                .addComponent(delete)
                .addGap(18, 18, 18)
                .addComponent(managePosts)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(promote)
                    .addComponent(demote)
                    .addComponent(delete)
                    .addComponent(managePosts))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void promoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promoteActionPerformed
        // TODO add your handling code here:
         
        String selectedMember = memberList.getSelectedValue();
        if (selectedMember == null) {
            JOptionPane.showMessageDialog(this, "No member selected!");
            return;
        }

      User member = null;
    for (User m : currentGroup.getMembers()) {
    if (m.getUsername().equals(selectedMember)) {
        member = m;
        break;
    }
}

        if (member == null) {
            JOptionPane.showMessageDialog(this, "Member not found in this group!");
            return;
        }

        manager.promoteToAdmin(member, currentGroup.getName());
        JOptionPane.showMessageDialog(this, selectedMember + " has been promoted to Admin.");
    
        
        
        
        
    }//GEN-LAST:event_promoteActionPerformed

    private void demoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demoteActionPerformed
        // TODO add your handling code here:
        String selectedAdmin = adminList.getSelectedValue();
        if (selectedAdmin == null) {
            JOptionPane.showMessageDialog(this, "No admin selected!");
            return;
        }
        
        User admin = null;
for (User a : currentGroup.getAdmins()) {
    if (a.getUsername().equals(selectedAdmin)) {
        admin = a;
        break;
    }
}
        
        
        
        if (admin == null) {
            JOptionPane.showMessageDialog(this, "Admin not found in this group!");
            return;
        }
        
        manager.promoteToAdmin(admin, currentGroup.getName());
        JOptionPane.showMessageDialog(this, selectedAdmin + " has been promoted to Admin.");
        
        
        
        
        
        
    }//GEN-LAST:event_demoteActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        
        manager.deleteGroup( currentGroup.getName());
         JOptionPane.showMessageDialog(null, "Group deleted successfully.");
         
        
        
        
        
        
        
        
    }//GEN-LAST:event_deleteActionPerformed

    private void managePostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePostsActionPerformed
        // TODO add your handling code here:
        
        ArrayList<Post>posts=currentGroup.getPosts();
        
      
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_managePostsActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton demote;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton managePosts;
    private javax.swing.JButton promote;
    // End of variables declaration//GEN-END:variables
}
