/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author yaras
 */
public class SuggestedGroups extends javax.swing.JFrame {

    Newsfeed n;
    GroupManagement manage = new GroupManagement();
    User currentuser;
    UserDataBase userDB = UserDataBase.getDatabase();
    RequestDatabase requestsDB = RequestDatabase.getinstance();
    GroupDataBase GDB = GroupDataBase.getInstance();

    /**
     * Creates new form SuggestedGroups
     */
    public SuggestedGroups(Newsfeed n, User currentuser) {
        this.n = n;
        this.currentuser = currentuser;
        
        initComponents();
        fillList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendrequest1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sendrequest1.setBackground(new java.awt.Color(255, 204, 255));
        sendrequest1.setText("Send Request");
        sendrequest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendrequest1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(list);

        jButton2.setBackground(new java.awt.Color(255, 204, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Suggested Groups");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sendrequest1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendrequest1)
                    .addComponent(jButton2))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void fillList() {

        ArrayList<Group> suggested = manage.getSuggestedGroups(currentuser.getUserId());

        DefaultListModel<String> model = new DefaultListModel();

        for (Group group : suggested) {
            model.addElement(group.getGroupName()); // Corrected to use group from the loop
        }


        list.setModel(model);
        jScrollPane1.setViewportView(list);

    }

    private void sendrequest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendrequest1ActionPerformed
        // TODO add your handling code here:

         int index = list.getSelectedIndex();
        if (index > -1) {
            String selectedGroupName = list.getSelectedValue();
            Group selectedGroup = GDB.getGroupByname(selectedGroupName); // Retrieve the selected group by name
            if (selectedGroup != null) {
                String senderId = currentuser.getUserId();
                manage.sendrequest(senderId, selectedGroup.getGroupId()); // Send join request
                JOptionPane.showMessageDialog(this, "Request sent successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                fillList(); // Refresh the list after sending the request
            } else {
                JOptionPane.showMessageDialog(this, "Group not found!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "You must select a group!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    


    }//GEN-LAST:event_sendrequest1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        n.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list;
    private javax.swing.JButton sendrequest;
    private javax.swing.JButton sendrequest1;
    // End of variables declaration//GEN-END:variables

}