/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.Group;
import Backend.Post;
import Backend.PostDataBase;
import Backend.User;
import Backend.UserDataBase;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author hp
 */
public class ViewPostFromNotification extends javax.swing.JFrame {

   Newsfeed n;
    private Group g;
    public ViewPostFromNotification(Newsfeed n, Group g) {
        initComponents();
        this.n = n;
        this.g = g;
        initUI();
    }
    
    private void initUI() {
        ArrayList<String> postIds = g.getPostIDs(); 
        postPanel.setLayout(new BorderLayout());

        if (postIds.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No posts found in the group.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String postId = postIds.get(0);
        PostDataBase postDatabase = PostDataBase.getInstance();
        Post post = postDatabase.GetPostById(postId);

        if (post == null) {
            JOptionPane.showMessageDialog(this, "Post not found.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JTextArea postContentArea = new JTextArea(post.getContent());
        postContentArea.setEditable(false);
        postContentArea.setWrapStyleWord(true);
        postContentArea.setLineWrap(true);

        postPanel.add(new JScrollPane(postContentArea), BorderLayout.CENTER);
        UserDataBase userDB = UserDataBase.getDatabase();
        User author = userDB.getUserById(post.getAuthorID());

        JPanel infoPanel = new JPanel();
        infoPanel.add(new JLabel("Group: " + g.getGroupName()));
        infoPanel.add(new JLabel("Posted by: " + author.getUsername()));
        add(infoPanel, BorderLayout.NORTH);
        postPanel.add(infoPanel, BorderLayout.NORTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        postPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Post");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        javax.swing.GroupLayout postPanelLayout = new javax.swing.GroupLayout(postPanel);
        postPanel.setLayout(postPanelLayout);
        postPanelLayout.setHorizontalGroup(
            postPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );
        postPanelLayout.setVerticalGroup(
            postPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(postPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(postPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        n.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel postPanel;
    // End of variables declaration//GEN-END:variables
}
